### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by ag2s20150909** [MetaCubeX/mihomo#312]
```
panic: interface conversion: interface {} is nil, not string

goroutine 121 [running]:
github.com/Dreamacro/clash/common/convert.ConvertsV2Ray({0xc0011a6000, 0x544, 0x580?})
        github.com/Dreamacro/clash/common/convert/converter.go:166 +0x474a
github.com/Dreamacro/clash/adapter/provider.proxiesParseAndFilter.func1({0xc0011a6000, 0x544, 0x580})
        github.com/Dreamacro/clash/adapter/provider/provider.go:270 +0xfc
github.com/Dreamacro/clash/component/resource.(*Fetcher[...]).Initial(0xc0001facb0)
        github.com/Dreamacro/clash/component/resource/fetcher.go:83 +0x36f
github.com/Dreamacro/clash/adapter/provider.(*proxySetProvider).Initial(0xc000151780)
        github.com/Dreamacro/clash/adapter/provider/provider.go:77 +0x28
github.com/Dreamacro/clash/hub/executor.loadProvider({0x1a4f8e74f40, 0xc00014a390})
        github.com/Dreamacro/clash/hub/executor/executor.go:226 +0xe7
github.com/Dreamacro/clash/hub/executor.loadProxyProvider.func1()
        github.com/Dreamacro/clash/hub/executor/executor.go:268 +0x88
created by github.com/Dreamacro/clash/hub/executor.loadProxyProvider
        github.com/Dreamacro/clash/hub/executor/executor.go:266 +0x90
```

**Comment by cubemaze** [comment]
@ag2s20150909 检查代理集配置
