### ISSUE TITLE
udp handle dead lock

### ISSUE THREAD

**Issue by ghost** [MetaCubeX/mihomo#313]
长期运行会挂起很多goroutine 问题出在[wait](https://github.com/MetaCubeX/Clash.Meta/blob/Meta/tunnel/tunnel.go#L252)

pprof -> goroutine : 11个goroutine一直卡住
```
11 @ 0x104630864 0x10465cc4c 0x10465cc2d 0x1046642f0 0x104d23fec 0x104660f54
#	0x10465cc2c	sync.runtime_notifyListWait+0x14c				runtime/sema.go:517
#	0x1046642ef	sync.(*Cond).Wait+0xcf						sync/cond.go:70
#	0x104d23feb	github.com/Dreamacro/clash/tunnel.handleUDPConn.func2+0x98b	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:283
```

pprof -> full goroutine stack dump   :  每个卡了50分钟依旧未释放
```
goroutine 59 [sync.Cond.Wait, 50 minutes]:
sync.runtime_notifyListWait(0x130134e90, 0xf)
	runtime/sema.go:517 +0x16c
sync.(*Cond).Wait(0x130134e80)
	sync/cond.go:70 +0xd0
github.com/Dreamacro/clash/tunnel.handleUDPConn.func2()
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:283 +0x98c
created by github.com/Dreamacro/clash/tunnel.handleUDPConn
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:280 +0x3c0

goroutine 60 [sync.Cond.Wait, 50 minutes]:
sync.runtime_notifyListWait(0x130134e90, 0x10)
	runtime/sema.go:517 +0x16c
sync.(*Cond).Wait(0x130134e80)
	sync/cond.go:70 +0xd0
github.com/Dreamacro/clash/tunnel.handleUDPConn.func2()
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:283 +0x98c
created by github.com/Dreamacro/clash/tunnel.handleUDPConn
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:280 +0x3c0

goroutine 61 [sync.Cond.Wait, 50 minutes]:
sync.runtime_notifyListWait(0x130134e90, 0x11)
	runtime/sema.go:517 +0x16c
sync.(*Cond).Wait(0x130134e80)
	sync/cond.go:70 +0xd0
github.com/Dreamacro/clash/tunnel.handleUDPConn.func2()
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:283 +0x98c
created by github.com/Dreamacro/clash/tunnel.handleUDPConn
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:280 +0x3c0

goroutine 62 [sync.Cond.Wait, 50 minutes]:
sync.runtime_notifyListWait(0x130134e90, 0x12)
	runtime/sema.go:517 +0x16c
sync.(*Cond).Wait(0x130134e80)
	sync/cond.go:70 +0xd0
github.com/Dreamacro/clash/tunnel.handleUDPConn.func2()
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:283 +0x98c
created by github.com/Dreamacro/clash/tunnel.handleUDPConn
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:280 +0x3c0

goroutine 63 [sync.Cond.Wait, 50 minutes]:
sync.runtime_notifyListWait(0x130134e90, 0x13)
	runtime/sema.go:517 +0x16c
sync.(*Cond).Wait(0x130134e80)
	sync/cond.go:70 +0xd0
github.com/Dreamacro/clash/tunnel.handleUDPConn.func2()
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:283 +0x98c
created by github.com/Dreamacro/clash/tunnel.handleUDPConn
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:280 +0x3c0

goroutine 64 [sync.Cond.Wait, 50 minutes]:
sync.runtime_notifyListWait(0x130134e90, 0x14)
	runtime/sema.go:517 +0x16c
sync.(*Cond).Wait(0x130134e80)
	sync/cond.go:70 +0xd0
github.com/Dreamacro/clash/tunnel.handleUDPConn.func2()
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:283 +0x98c
created by github.com/Dreamacro/clash/tunnel.handleUDPConn
	github.com/Dreamacro/clash@v0.0.0/tunnel/tunnel.go:280 +0x3c0
````

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
