### ISSUE TITLE
开启sniffer后会占用大量udp端口

### ISSUE THREAD

**Issue by ag2s20150909** [MetaCubeX/mihomo#466]
使用一段时间后会导致Gradle构建失败
```
* Exception is:
org.gradle.api.UncheckedIOException: java.net.SocketException: No buffer space available (maximum connections reached?): Cannot bind
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:62)
	at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:41)
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.<init>(FileLockCommunicator.java:51)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.getCommunicator(DefaultFileLockContentionHandler.java:263)
	at org.gradle.cache.internal.locklistener.DefaultFileLockContentionHandler.reservePort(DefaultFileLockContentionHandler.java:255)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:109)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:96)
	at org.gradle.cache.internal.DefaultFileLockManager.lock(DefaultFileLockManager.java:91)
	at org.gradle.cache.internal.OnDemandFileAccess.updateFile(OnDemandFileAccess.java:51)
	at org.gradle.cache.internal.SimpleStateCache.update(SimpleStateCache.java:87)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator$1.create(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:50)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.doUpdate(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:67)
	at org.gradle.cache.internal.FileIntegrityViolationSuppressingPersistentStateCacheDecorator.update(FileIntegrityViolationSuppressingPersistentStateCacheDecorator.java:47)
	at org.gradle.launcher.daemon.registry.PersistentDaemonRegistry.store(PersistentDaemonRegistry.java:232)
	at org.gradle.launcher.daemon.server.DaemonRegistryUpdater.onStart(DaemonRegistryUpdater.java:80)
	at org.gradle.launcher.daemon.server.Daemon.start(Daemon.java:171)
	at org.gradle.launcher.daemon.bootstrap.DaemonMain.doAction(DaemonMain.java:125)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.daemon.bootstrap.GradleDaemon.main(GradleDaemon.java:22)
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): Cannot bind
	at java.base/java.net.DualStackPlainDatagramSocketImpl.socketBind(Native Method)
	at java.base/java.net.DualStackPlainDatagramSocketImpl.bind0(DualStackPlainDatagramSocketImpl.java:84)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:135)
	at java.base/java.net.DatagramSocket.bind(DatagramSocket.java:394)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:244)
	at java.base/java.net.DatagramSocket.<init>(DatagramSocket.java:301)
	at org.gradle.cache.internal.locklistener.FileLockCommunicator.<init>(FileLockCommunicator.java:49)
	... 22 more

```

**Comment by railzy** [comment]
尝试关了 sniffer ，发现依然出现大量端口占用。

**Comment by xishang0128** [comment]
考虑到这个 issues 没有使用正确的模板格式，我们决定关闭它。 
 
如果你有需要请遵守模版开启新的 issues。
 
Considering that this issue did not use the correct template format, we decided to close it. 
 
If you need to, please follow the template to open new issues.
