### ISSUE TITLE
[Bug] panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ag2s20150909** [MetaCubeX/mihomo#555]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-51e9f35

### Clash config

```yaml
无关
```

### Clash log

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xcaf5d7]

goroutine 8022 [running]:
github.com/Dreamacro/clash/tunnel.handleUDPToLocal({0x1f1ba165a28, 0xc0020c17b8}, {0x17463f0?, 0xc000892d20}, {0xc003190c30?, 0xc0017de0c0?}, {{0x0?, 0x0?}, 0xc000004078?}, {{0x0, ...}, ...})
        github.com/Dreamacro/clash/tunnel/connection.go:55 +0x3f7
created by github.com/Dreamacro/clash/tunnel.handleUDPConn.func2
        github.com/Dreamacro/clash/tunnel/tunnel.go:389 +0xd55
```

### Description

无关

**Comment by Skyxim** [comment]
@ag2s20150909 尝试下 alpha 分支最新版本
